"use client";

import { useEffect, useState, type ReactNode } from "react";
import { Check, ChevronDown, Clock3, Copy, ExternalLink, Laptop, Link2, LoaderCircle, RefreshCw, RotateCcw, ShieldCheck, Trash2, Webhook, Zap } from "lucide-react";
import { chuskyApi, type AccountOverview, type Model, type TelegramLinkCode, type Toolkit, type Trigger } from "@/lib/chusky-api";
import { Button, Card, PageHeading, Status } from "./app-shell";
import { ConfirmDialog } from "./confirm-dialog";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";

type PageKind = "approvals" | "apps" | "reminders" | "jobs" | "memory" | "scratchpad" | "triggers" | "workspace" | "devices" | "settings";

const copy: Record<PageKind, { eyebrow: string; title: string; description: string }> = {
  approvals: { eyebrow: "Safety center", title: "Approvals", description: "Review externally visible actions before Chusky executes them." },
  apps: { eyebrow: "Channel connections", title: "Connected apps", description: "See the channels currently verified for your Chusky account." },
  reminders: { eyebrow: "One-time automation", title: "Reminders", description: "Durable reminders delivered when they are due." },
  jobs: { eyebrow: "Scheduled automation", title: "Recurring jobs", description: "Recurring schedules currently stored for your account." },
  memory: { eyebrow: "Long-term context", title: "Memory", description: "Facts and preferences you explicitly asked Chusky to remember." },
  scratchpad: { eyebrow: "Private working notes", title: "Scratchpad", description: "Temporary notes saved in your private Chusky session." },
  triggers: { eyebrow: "Real-time events", title: "Triggers", description: "Event trigger IDs owned by this account." },
  workspace: { eyebrow: "Daytona workspace", title: "Workspace", description: "The isolated computer workspace attached to your account." },
  devices: { eyebrow: "CLI access", title: "Devices", description: "Terminals currently linked to your Chusky account." },
  settings: { eyebrow: "Account configuration", title: "Settings", description: "Live account defaults and runtime preferences." },
};

function date(value: string) { return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function Empty({ children }: { children: ReactNode }) { return <p className="p-4 text-xs text-muted-foreground sm:p-5">{children}</p>; }
function Offline({ retry }: { retry: () => void }) { return <Card className="flex flex-col items-start gap-3 p-4"><Status tone="amber">Backend unavailable</Status><p className="text-xs text-muted-foreground">This page needs the authenticated Chusky API to load your private data.</p><Button secondary onClick={retry}><RefreshCw size={13} /> Retry</Button></Card>; }

export function AccountDataPage({ kind }: { kind: PageKind }) {
  const [data, setData] = useState<AccountOverview>();
  const [offline, setOffline] = useState(false);
  const [busy, setBusy] = useState<string>();
  const load = async () => { setOffline(false); try { setData(await chuskyApi.account.get()); } catch { setOffline(true); } };
  useEffect(() => { void load(); }, []);
  const decide = async (id: string, decision: "approve" | "deny") => { setBusy(id); try { await chuskyApi.approvals.decide(id, decision); await load(); } finally { setBusy(undefined); } };
  const heading = copy[kind];
  return <><PageHeading eyebrow={heading.eyebrow} title={heading.title} description={heading.description} action={<Button secondary onClick={() => void load()}><RefreshCw size={13} /> Refresh</Button>} />{offline ? <Offline retry={() => void load()} /> : !data ? <Card className="flex items-center gap-3 p-4 text-xs text-muted-foreground sm:p-5"><LoaderCircle size={15} className="animate-spin" /> Loading your saved data…</Card> : <Content kind={kind} data={data} decide={decide} busy={busy} />}</>;
}

function Content({ kind, data, decide, busy }: { kind: PageKind; data: AccountOverview; decide: (id: string, decision: "approve" | "deny") => Promise<void>; busy?: string }) {
  if (kind === "approvals") return <Card>{data.approvals.length ? data.approvals.map((item) => <div key={item.id} className="border-b border-foreground/10 p-3.5 last:border-0 sm:p-4"><div className="flex flex-col gap-3 md:flex-row md:items-start"><ShieldCheck className="mt-1 shrink-0 text-amber-600" size={17} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xs font-medium">{item.toolSlug}</h2><Status tone="amber">Expires {date(item.expiresAt)}</Status></div><p className="mt-2 break-words text-xs text-muted-foreground">{item.request}</p><p className="mt-2 break-all font-mono text-[9px] text-muted-foreground">{item.id}{item.channelProvider ? ` · ${item.channelProvider}` : ""}</p></div><div className="flex flex-wrap gap-2"><Button secondary onClick={() => void decide(item.id, "deny")}><Trash2 size={12} /> Deny</Button><Button onClick={() => void decide(item.id, "approve")}><Check size={12} /> {busy === item.id ? "Working" : "Approve"}</Button></div></div></div>) : <Empty>No pending approvals. Chusky will show risky actions here before execution.</Empty>}</Card>;
  if (kind === "apps") return <AppsPanel channels={data.channels} />;
  if (kind === "reminders") return <Card>{data.reminders.length ? data.reminders.map((item) => <Row key={item.id} icon={<Clock3 size={15} />} title={item.text} detail={`Runs ${date(item.runAt)}`} meta={`Created ${date(item.createdAt)}`} status={item.status} />) : <Empty>No reminders saved yet.</Empty>}</Card>;
  if (kind === "jobs") return <Card>{data.jobs.length ? data.jobs.map((item) => <Row key={item.id} icon={<RotateCcw size={15} />} title={item.text} detail={item.cron} meta={`Created ${date(item.createdAt)}`} status={item.status} />) : <Empty>No recurring jobs saved yet.</Empty>}</Card>;
  if (kind === "memory") return <Card>{data.memory.length ? data.memory.map((item) => <Row key={item.id} icon={<Zap size={15} />} title={item.key} detail={item.value} meta={`${item.category} · ${Math.round(item.confidence * 100)}% confidence · ${date(item.updatedAt)}`} />) : <Empty>No explicit memories saved yet.</Empty>}</Card>;
  if (kind === "scratchpad") return <Card>{data.scratchpad.length ? data.scratchpad.map((item) => <Row key={item.key} icon={<ExternalLink size={15} />} title={item.key} detail={item.content} meta={`Updated ${date(item.updatedAt)}`} />) : <Empty>Your scratchpad is empty.</Empty>}</Card>;
  if (kind === "triggers") return <TriggersPanel />;
  if (kind === "devices") return <Card>{data.devices.length ? data.devices.map((item) => <Row key={item.name} icon={<Laptop size={15} />} title={item.name} detail={`Last seen ${date(item.lastSeenAt)}`} meta={`Linked ${date(item.createdAt)}`} status="Active" />) : <Empty>No CLI devices are linked.</Empty>}</Card>;
  if (kind === "workspace") return <Card className="p-4">{data.workspace ? <div className="space-y-3"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center border border-foreground/10"><Laptop size={17} /></span><div className="min-w-0"><h2 className="truncate text-xs font-medium">{data.workspace.name}</h2><p className="mt-1 truncate text-[11px] text-muted-foreground">{data.workspace.sandboxId}</p></div><Status tone={data.workspace.lastKnownState === "running" ? "green" : "amber"}>{data.workspace.lastKnownState || "available"}</Status></div><div className="grid gap-3 text-[11px] sm:grid-cols-3"><Info label="PTY sessions" value={String(data.workspace.ptySessions)} /><Info label="Updated" value={date(data.workspace.updatedAt)} /><Info label="Browser" value={data.workspace.lastUrl || "No page saved"} /></div></div> : <Empty>No Daytona workspace has been created for this account.</Empty>}</Card>;
  return <div className="grid gap-4 lg:grid-cols-2"><SettingsPanel initialModel={data.model} initialVoice={data.voiceReplies} /><TelegramLink linked={data.telegramLink.linked} /><Card className="p-4 sm:p-5"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Developer webhooks</p>{data.webhooks.length ? data.webhooks.map((item) => <Row key={item.id} icon={<Webhook size={15} />} title={item.url} detail={item.id} meta={`Created ${date(item.createdAt)}`} />) : <Empty>No developer webhooks configured.</Empty>}</Card></div>;
}

function SettingsPanel({ initialModel, initialVoice }: { initialModel: string; initialVoice: boolean }) {
  const [model, setModel] = useState(initialModel); const [voice, setVoice] = useState(initialVoice); const [models, setModels] = useState<Model[]>([]); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string>();
  useEffect(() => { void chuskyApi.account.models().then((result) => setModels(result.data)).catch(() => setMessage("Model list is temporarily unavailable.")); }, []);
  const update = async (input: { model?: string; voiceReplies?: boolean }) => { setBusy(true); setMessage(undefined); try { const next = await chuskyApi.account.updatePreferences(input); setModel(next.model); setVoice(next.voiceReplies); setOpen(false); setMessage("Saved across Telegram, CLI, and web."); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save this preference."); } finally { setBusy(false); } };
  return <Card className="p-4 sm:p-5"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Runtime preferences</p><div className="mt-4 space-y-4"><div><label className="text-xs text-muted-foreground">Selected model</label><div className="relative mt-1.5"><Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button type="button" disabled={busy} aria-expanded={open} className="flex min-h-9 w-full items-center justify-between border border-foreground/15 px-2.5 py-2 text-left text-xs hover:border-foreground/40"><span className="truncate">{model}</span><ChevronDown size={14} /></button></PopoverTrigger><PopoverContent align="start" sideOffset={5} className="max-h-64 w-[min(24rem,calc(100vw-1rem))] overflow-auto p-1">{models.map((item) => <button key={item.id} type="button" onClick={() => void update({ model: item.id })} className="block min-h-8 w-full px-2.5 py-2 text-left text-xs hover:bg-foreground/5"><span className="block truncate">{item.name}</span><span className="mt-0.5 block truncate font-mono text-[9px] text-muted-foreground">{item.id}</span></button>)}{!models.length && <p className="p-3 text-xs text-muted-foreground">Loading models…</p>}</PopoverContent></Popover></div></div><div className="flex items-center justify-between gap-3 border-t border-foreground/10 pt-3"><div className="min-w-0"><p className="text-xs">Voice replies</p><p className="mt-1 text-[10px] text-muted-foreground">Read Chusky responses aloud where supported.</p></div><button type="button" role="switch" aria-checked={voice} disabled={busy} onClick={() => void update({ voiceReplies: !voice })} className={`relative h-6 w-11 shrink-0 rounded-full transition-colors ${voice ? "bg-foreground" : "bg-foreground/15"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-background transition-transform ${voice ? "translate-x-6" : "translate-x-1"}`} /></button></div>{message && <p className="text-[11px] text-muted-foreground">{message}</p>}</div></Card>;
}

function AppsPanel({ channels }: { channels: AccountOverview["channels"] }) {
  const [items, setItems] = useState<Toolkit[]>([]); const [busy, setBusy] = useState<string>(); const [error, setError] = useState<string>();
  const load = async () => { try { setItems((await chuskyApi.apps.list()).data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load apps."); } };
  useEffect(() => { void load(); }, []);
  const connect = async (slug: string) => { setBusy(slug); setError(undefined); try { const result = await chuskyApi.apps.connect(slug); window.open(result.url, "_blank", "noopener,noreferrer"); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create a connection link."); } finally { setBusy(undefined); } };
  const connectedChannels = channels.map((item) => item.provider.toLowerCase());
  return <div className="space-y-3.5"><Card><div className="border-b border-foreground/10 px-3.5 py-2.5 text-[11px] text-muted-foreground sm:px-4">Composio apps · connection links open securely in a new tab</div>{items.length ? items.map((item) => <div key={item.slug} className="flex min-w-0 items-center gap-2.5 border-b border-foreground/10 p-3.5 last:border-0 sm:p-4"><div className="flex h-8 w-8 shrink-0 items-center justify-center border border-foreground/10 text-xs">{item.name.slice(0, 1)}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium">{item.name}</p><p className="mt-1 truncate font-mono text-[10px] text-muted-foreground">{item.slug}</p></div>{item.connected ? <Status>Connected</Status> : <Button secondary disabled={busy === item.slug} onClick={() => void connect(item.slug)}>{busy === item.slug ? "Opening…" : "Connect"}</Button>}</div>) : <Empty>{error || "Loading connected apps…"}</Empty>}</Card><Card className="p-4 text-xs text-muted-foreground sm:p-5">{connectedChannels.length ? `${connectedChannels.length} verified channel connection${connectedChannels.length === 1 ? "" : "s"} also available.` : "Channel connections are managed separately from Composio apps."}{error && <p className="mt-2 text-amber-700">{error}</p>}</Card></div>;
}

function TriggersPanel() {
  const [items, setItems] = useState<Trigger[]>([]); const [slug, setSlug] = useState(""); const [config, setConfig] = useState("{}"); const [busy, setBusy] = useState<string>(); const [error, setError] = useState<string>(); const [confirmId, setConfirmId] = useState<string>();
  const load = async () => { try { setItems((await chuskyApi.triggers.list()).data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load triggers."); } };
  useEffect(() => { void load(); }, []);
  const create = async () => { setBusy("create"); setError(undefined); try { const parsed = JSON.parse(config); await chuskyApi.triggers.create(slug.trim().toUpperCase(), parsed); setSlug(""); setConfig("{}"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Trigger configuration must be valid JSON."); } finally { setBusy(undefined); } };
  const toggle = async (item: Trigger) => { setBusy(item.id); try { await chuskyApi.triggers.setEnabled(item.id, item.status.toLowerCase() !== "active" && item.status.toLowerCase() !== "enabled"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not update trigger."); } finally { setBusy(undefined); } };
  const remove = async (id: string) => { setBusy(id); try { await chuskyApi.triggers.remove(id); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not delete trigger."); } finally { setBusy(undefined); } };
  const confirmedTrigger = items.find((item) => item.id === confirmId);
  return <div className="space-y-3.5"><Card className="p-4 sm:p-5"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Create trigger</p><div className="mt-3 grid gap-2.5 md:grid-cols-[1fr_1.4fr_auto]"><input value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="GITHUB_COMMIT_EVENT" className="min-h-9 min-w-0 border border-foreground/15 bg-transparent px-2.5 py-2 text-xs outline-none" /><input value={config} onChange={(event) => setConfig(event.target.value)} placeholder='{"repo":"owner/name"}' className="min-h-9 min-w-0 border border-foreground/15 bg-transparent px-2.5 py-2 font-mono text-xs outline-none" /><Button disabled={!slug.trim() || busy === "create"} onClick={() => void create()}>{busy === "create" ? "Creating…" : "Create"}</Button></div>{error && <p className="mt-3 text-xs text-amber-700">{error}</p>}</Card><Card>{items.length ? items.map((item) => <div key={item.id} className="flex min-w-0 flex-col gap-2.5 border-b border-foreground/10 p-3.5 last:border-0 sm:flex-row sm:items-center sm:p-4"><Webhook size={15} className="shrink-0 text-muted-foreground" /><div className="min-w-0 flex-1"><p className="break-all text-xs font-medium">{item.slug || item.id}</p><p className="mt-1 break-all font-mono text-[10px] text-muted-foreground">{item.id}</p></div><div className="flex flex-wrap items-center gap-2"><Status tone={item.status.toLowerCase() === "active" || item.status.toLowerCase() === "enabled" ? "green" : "gray"}>{item.status}</Status><Button secondary disabled={busy === item.id} onClick={() => void toggle(item)}>{item.status.toLowerCase() === "active" || item.status.toLowerCase() === "enabled" ? "Disable" : "Enable"}</Button><Button secondary disabled={busy === item.id} onClick={() => setConfirmId(item.id)}><Trash2 size={12} /> Delete</Button></div></div>) : <Empty>No triggers yet. Create one above or ask Chusky in Telegram.</Empty>}</Card>{confirmedTrigger && <ConfirmDialog open={Boolean(confirmId)} onOpenChange={(open) => !open && setConfirmId(undefined)} title={`Delete ${confirmedTrigger.slug || confirmedTrigger.id}?`} description="This trigger and its configuration will be permanently removed." confirmLabel="Delete trigger" destructive onConfirm={() => { const id = confirmedTrigger.id; setConfirmId(undefined); return remove(id); }} />}</div>;
}

function TelegramLink({ linked }: { linked: boolean }) {
  const [link, setLink] = useState<TelegramLinkCode>();
  const [busy, setBusy] = useState(false);
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState<string>();
  const create = async () => {
    setBusy(true); setError(undefined); setCopied(false);
    try { setLink(await chuskyApi.account.createTelegramLink()); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create a Telegram link code."); }
    finally { setBusy(false); }
  };
  const copy = async () => {
    if (!link) return;
    try { await navigator.clipboard.writeText(`/link ${link.code}`); setCopied(true); }
    catch { setError("Copy the command manually, then send it in Telegram."); }
  };
  return <Card className="p-4 sm:p-5"><div className="flex items-start gap-2.5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-foreground/10"><Link2 size={15} /></span><div className="min-w-0 flex-1"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Telegram workspace</p><h2 className="mt-1.5 text-sm font-medium">{linked ? "Linked to Telegram" : "Link your Telegram workspace"}</h2><p className="mt-1.5 text-xs leading-5 text-muted-foreground">{linked ? "This dashboard now reads and controls the same private Chusky workspace as your Telegram account." : "Generate a one-time code, then send it from the Telegram account that already uses Chusky."}</p>{!linked && <div className="mt-3 space-y-2.5">{link ? <div className="rounded-lg border border-foreground/10 bg-muted/30 p-2.5"><div className="flex items-center justify-between gap-2.5"><code className="min-w-0 break-all text-xs">/link {link.code}</code><Button secondary aria-label="Copy Telegram link command" onClick={() => void copy()}>{copied ? <Check size={14} /> : <Copy size={14} />}</Button></div><p className="mt-2 text-[10px] text-muted-foreground">Send this command in Telegram before {date(link.expiresAt)}. It works once.</p></div> : <Button onClick={() => void create()} disabled={busy}>{busy ? <LoaderCircle size={14} className="animate-spin" /> : <Link2 size={14} />}{busy ? "Creating code" : "Create link code"}</Button>}{error && <p className="text-xs text-amber-700">{error}</p>}</div>}</div></div></Card>;
}

function Row({ icon, title, detail, meta, status }: { icon: ReactNode; title: string; detail?: string; meta?: string; status?: string }) { return <div className="flex min-w-0 items-start gap-2.5 border-b border-foreground/10 px-3.5 py-2.5 last:border-0 sm:px-4 sm:py-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center border border-foreground/10 text-muted-foreground">{icon}</span><div className="min-w-0 flex-1"><p className="break-words text-xs font-medium">{title}</p>{detail && <p className="mt-1 break-words text-[11px] text-muted-foreground">{detail}</p>}{meta && <p className="mt-1.5 break-words text-[9px] text-muted-foreground">{meta}</p>}</div>{status && <Status tone={status === "failed" ? "amber" : status === "cancelled" ? "gray" : "green"}>{status}</Status>}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="flex items-start justify-between gap-4 border-b border-foreground/10 pb-3 text-xs last:border-0"><span className="text-muted-foreground">{label}</span><span className="max-w-[65%] break-words text-right">{value}</span></div>; }
