"use client";

import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import { Clock3, LoaderCircle, RefreshCw, RotateCcw, Save, Trash2, Zap } from "lucide-react";
import { chuskyApi, type Job, type MemoryFact, type Reminder, type ScratchpadNote } from "@/lib/chusky-api";
import { Button, Card, PageHeading, Status } from "./app-shell";

const date = (value: string) => new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export function RemindersPage() {
  const [items, setItems] = useState<Reminder[]>([]); const [text, setText] = useState(""); const [delay, setDelay] = useState("60"); const [busy, setBusy] = useState<string>(); const [error, setError] = useState<string>();
  const load = async () => { try { setItems((await chuskyApi.reminders.list()).data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load reminders."); } };
  useEffect(() => { void load(); }, []);
  const create = async () => { if (!text.trim()) return; setBusy("create"); setError(undefined); try { const item = await chuskyApi.reminders.create({ text: text.trim(), delaySeconds: Math.max(1, Number(delay) || 60) }); setItems((current) => [...current, item].sort((a, b) => +new Date(a.runAt) - +new Date(b.runAt))); setText(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create reminder."); } finally { setBusy(undefined); } };
  const cancel = async (item: Reminder) => { setBusy(item.id); try { await chuskyApi.reminders.cancel(item.id); setItems((current) => current.filter((candidate) => candidate.id !== item.id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not cancel reminder."); } finally { setBusy(undefined); } };
  return <><PageHeading eyebrow="One-time automation" title="Reminders" description="Create durable reminders that continue running after you close the browser." action={<Button secondary onClick={() => void load()}><RefreshCw size={13} /> Refresh</Button>} />{error && <Error text={error} />}<Card className="mb-4 p-4"><div className="grid gap-2 sm:grid-cols-[1fr_140px_auto]"><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Remind me to check the launch metrics" className="min-h-9 border border-foreground/15 bg-transparent px-2.5 text-xs outline-none" /><label className="flex items-center gap-2 border border-foreground/15 px-2.5 text-[10px] text-muted-foreground"><input value={delay} onChange={(event) => setDelay(event.target.value)} type="number" min="1" className="w-full bg-transparent text-xs text-foreground outline-none" /> sec</label><Button disabled={!text.trim() || busy === "create"} onClick={() => void create()}>{busy === "create" ? <LoaderCircle size={13} className="animate-spin" /> : <Clock3 size={13} />} Add</Button></div></Card><Card>{items.length ? items.map((item) => <div key={item.id} className="flex items-center gap-3 border-b border-foreground/10 p-4 last:border-0"><Clock3 size={15} className="shrink-0 text-muted-foreground" /><div className="min-w-0 flex-1"><p className="break-words text-xs font-medium">{item.text}</p><p className="mt-1 text-[10px] text-muted-foreground">Runs {date(item.runAt)} · {item.id}</p></div><Button secondary disabled={busy === item.id} onClick={() => void cancel(item)}><Trash2 size={12} /> Cancel</Button></div>) : <Empty>No reminders saved yet.</Empty>}</Card></>;
}

export function JobsPage() {
  const [items, setItems] = useState<Job[]>([]); const [text, setText] = useState(""); const [cron, setCron] = useState("0 9 * * *"); const [busy, setBusy] = useState<string>(); const [error, setError] = useState<string>();
  const load = async () => { try { setItems((await chuskyApi.jobs.list()).data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load recurring jobs."); } };
  useEffect(() => { void load(); }, []);
  const create = async () => { if (!text.trim() || !cron.trim()) return; setBusy("create"); setError(undefined); try { const item = await chuskyApi.jobs.create({ text: text.trim(), cron: cron.trim() }); setItems((current) => [item, ...current]); setText(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create recurring job."); } finally { setBusy(undefined); } };
  const cancel = async (item: Job) => { setBusy(item.id); try { await chuskyApi.jobs.cancel(item.id); setItems((current) => current.filter((candidate) => candidate.id !== item.id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not cancel recurring job."); } finally { setBusy(undefined); } };
  return <><PageHeading eyebrow="Scheduled automation" title="Recurring jobs" description="Manage schedules backed by QStash and keep their durable state visible." action={<Button secondary onClick={() => void load()}><RefreshCw size={13} /> Refresh</Button>} />{error && <Error text={error} />}<Card className="mb-4 p-4"><div className="grid gap-2 sm:grid-cols-[1fr_180px_auto]"><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Send me a metrics digest" className="min-h-9 border border-foreground/15 bg-transparent px-2.5 text-xs outline-none" /><input value={cron} onChange={(event) => setCron(event.target.value)} placeholder="0 9 * * *" className="min-h-9 border border-foreground/15 bg-transparent px-2.5 font-mono text-xs outline-none" /><Button disabled={!text.trim() || !cron.trim() || busy === "create"} onClick={() => void create()}>{busy === "create" ? <LoaderCircle size={13} className="animate-spin" /> : <RotateCcw size={13} />} Schedule</Button></div><p className="mt-2 text-[10px] text-muted-foreground">Use standard five-field cron in the scheduler timezone.</p></Card><Card>{items.length ? items.map((item) => <div key={item.id} className="flex items-center gap-3 border-b border-foreground/10 p-4 last:border-0"><RotateCcw size={15} className="shrink-0 text-muted-foreground" /><div className="min-w-0 flex-1"><p className="break-words text-xs font-medium">{item.text}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{item.cron} · {item.id}</p></div><Status>Active</Status><Button secondary disabled={busy === item.id} onClick={() => void cancel(item)}><Trash2 size={12} /> Cancel</Button></div>) : <Empty>No recurring jobs saved yet.</Empty>}</Card></>;
}

export function MemoryPage() {
  const [items, setItems] = useState<MemoryFact[]>([]); const [category, setCategory] = useState("fact"); const [key, setKey] = useState(""); const [value, setValue] = useState(""); const [busy, setBusy] = useState<string>(); const [error, setError] = useState<string>();
  const load = async () => { try { setItems((await chuskyApi.memory.list()).data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load memory."); } };
  useEffect(() => { void load(); }, []);
  const save = async () => { if (!key.trim() || !value.trim()) return; setBusy("save"); setError(undefined); try { const item = await chuskyApi.memory.save({ category, key: key.trim(), value: value.trim() }); setItems((current) => [item, ...current.filter((candidate) => candidate.id !== item.id && !(candidate.category === item.category && candidate.key === item.key))]); setKey(""); setValue(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save memory."); } finally { setBusy(undefined); } };
  const remove = async (item: MemoryFact) => { setBusy(item.id); try { await chuskyApi.memory.remove(item.id); setItems((current) => current.filter((candidate) => candidate.id !== item.id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not remove memory."); } finally { setBusy(undefined); } };
  return <><PageHeading eyebrow="Long-term context" title="Memory" description="Explicit facts and preferences available to Chusky. Save only information you intend to persist." action={<Button secondary onClick={() => void load()}><RefreshCw size={13} /> Refresh</Button>} />{error && <Error text={error} />}<Card className="mb-4 p-4"><div className="grid gap-2 sm:grid-cols-[150px_1fr_1fr_auto]"><select value={category} onChange={(event) => setCategory(event.target.value)} className="min-h-9 border border-foreground/15 bg-background px-2 text-xs"><option value="fact">Fact</option><option value="preference">Preference</option><option value="business">Business</option><option value="project">Project</option><option value="negative">Do not</option></select><input value={key} onChange={(event) => setKey(event.target.value)} placeholder="Key" className="min-h-9 border border-foreground/15 bg-transparent px-2.5 text-xs outline-none" /><input value={value} onChange={(event) => setValue(event.target.value)} placeholder="Value" className="min-h-9 border border-foreground/15 bg-transparent px-2.5 text-xs outline-none" /><Button disabled={!key.trim() || !value.trim() || busy === "save"} onClick={() => void save()}>{busy === "save" ? <LoaderCircle size={13} className="animate-spin" /> : <Save size={13} />} Save</Button></div></Card><Card>{items.length ? items.map((item) => <div key={item.id} className="flex items-start gap-3 border-b border-foreground/10 p-4 last:border-0"><Zap size={15} className="mt-0.5 shrink-0 text-muted-foreground" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-xs font-medium">{item.key}</p><span className="font-mono text-[9px] text-muted-foreground">{item.category}</span></div><p className="mt-1 break-words text-xs text-muted-foreground">{item.value}</p><p className="mt-1 text-[10px] text-muted-foreground">{Math.round(item.confidence * 100)}% confidence · Updated {date(item.updatedAt)}</p></div><Button secondary disabled={busy === item.id} onClick={() => void remove(item)}><Trash2 size={12} /> Forget</Button></div>) : <Empty>No explicit memories saved yet.</Empty>}</Card></>;
}

export function ScratchpadPage() {
  const [items, setItems] = useState<ScratchpadNote[]>([]); const [key, setKey] = useState(""); const [content, setContent] = useState(""); const [busy, setBusy] = useState<string>(); const [error, setError] = useState<string>();
  const load = async () => { try { setItems((await chuskyApi.scratchpad.list()).data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load scratchpad."); } };
  useEffect(() => { void load(); }, []);
  const save = async () => { if (!key.trim() || !content.trim()) return; setBusy("save"); setError(undefined); try { const item = await chuskyApi.scratchpad.save(key.trim(), content); setItems((current) => [item, ...current.filter((candidate) => candidate.key !== item.key)]); setKey(""); setContent(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save note."); } finally { setBusy(undefined); } };
  const remove = async (item: ScratchpadNote) => { setBusy(item.key); try { await chuskyApi.scratchpad.remove(item.key); setItems((current) => current.filter((candidate) => candidate.key !== item.key)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not remove note."); } finally { setBusy(undefined); } };
  return <><PageHeading eyebrow="Private working notes" title="Scratchpad" description="Private notes for active work. They stay separate from durable memory." action={<Button secondary onClick={() => void load()}><RefreshCw size={13} /> Refresh</Button>} />{error && <Error text={error} />}<Card className="mb-4 p-4"><div className="grid gap-2"><input value={key} onChange={(event) => setKey(event.target.value)} placeholder="Note name" className="min-h-9 border border-foreground/15 bg-transparent px-2.5 text-xs outline-none" /><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Write a private working note…" rows={4} className="resize-y border border-foreground/15 bg-transparent px-2.5 py-2 text-xs outline-none" /><Button disabled={!key.trim() || !content.trim() || busy === "save"} onClick={() => void save()}>{busy === "save" ? <LoaderCircle size={13} className="animate-spin" /> : <Save size={13} />} Save note</Button></div></Card><Card>{items.length ? items.map((item) => <div key={item.key} className="flex items-start gap-3 border-b border-foreground/10 p-4 last:border-0"><div className="min-w-0 flex-1"><p className="text-xs font-medium">{item.key}</p><p className="mt-1 whitespace-pre-wrap break-words text-xs text-muted-foreground">{item.content}</p><p className="mt-1 text-[10px] text-muted-foreground">Updated {date(item.updatedAt)}</p></div><Button secondary disabled={busy === item.key} onClick={() => void remove(item)}><Trash2 size={12} /> Clear</Button></div>) : <Empty>Your scratchpad is empty.</Empty>}</Card></>;
}

function Error({ text }: { text: string }) { return <Card className="mb-4 border-amber-300 bg-amber-50 p-3.5 text-xs text-amber-900">{text}</Card>; }
function Empty({ children }: { children: ReactNode }) { return <p className="p-5 text-xs text-muted-foreground">{children}</p>; }
