"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, CircleAlert, GitBranch, RefreshCw, ShieldCheck, Timer } from "lucide-react";
import { chuskyApi, type Mission, type MissionProof, type OutcomePackage } from "@/lib/chusky-api";
import { Button, Card, PageHeading, Status } from "./app-shell";
import { useLiveData } from "@/lib/live-sync";
import { MarkdownMessage } from "./markdown-message";

const tone = (status: Mission["status"]): "green" | "amber" | "gray" => status === "completed" ? "green" : ["blocked", "failed", "paused", "waiting"].includes(status) ? "amber" : "gray";
const date = (value: number) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
const short = (value: string, max = 180) => value.length > max ? `${value.slice(0, max - 1)}…` : value;
type MissionDetail = { mission: Mission; proof?: MissionProof; events: Mission["events"] };

export function MissionsPage() {
  const [missions, setMissions] = useState<Mission[]>([]);
  const [selected, setSelected] = useState<MissionDetail>();
  const [offline, setOffline] = useState(false);
  const [busy, setBusy] = useState<string>();
  const [detailBusy, setDetailBusy] = useState<string>();
  const [outcomes, setOutcomes] = useState<OutcomePackage[]>([]);
  const load = async () => { setOffline(false); try { setMissions((await chuskyApi.missions.list()).data); } catch { setOffline(true); } };
  const loadDetail = async (mission: Mission) => { setDetailBusy(mission.id); try { const [fresh, proof, events] = await Promise.all([chuskyApi.missions.get(mission.id), chuskyApi.missions.proof(mission.id).catch(() => undefined), chuskyApi.missions.events(mission.id).catch(() => ({ data: mission.events }))]); setMissions((current) => current.map((item) => item.id === fresh.id ? fresh : item)); setSelected({ mission: fresh, proof, events: events.data }); } finally { setDetailBusy(undefined); } };
  useEffect(() => { void load(); void chuskyApi.outcomes.list().then((result) => setOutcomes(result.data)).catch(() => setOutcomes([])); }, []);
  useLiveData(load);
  const act = async (mission: Mission, action: "pause" | "resume" | "cancel" | "repair") => { setBusy(mission.id); try { const next = action === "repair" ? await chuskyApi.missions.repair(mission.id, { reason: "Operator requested mission recovery from the dashboard." }) : await chuskyApi.missions[action](mission.id); setMissions((current) => current.map((item) => item.id === next.id ? next : item)); await loadDetail(next); } finally { setBusy(undefined); } };
  return <div className="min-w-0">
    <PageHeading eyebrow="Autonomous work" title="Missions" description="Durable work with checkpoints, budgets, waits, evidence, and explicit recovery controls." action={<Button secondary onClick={() => void load()}><RefreshCw size={13} /> Refresh</Button>} />
    {outcomes.length > 0 && <Card className="mb-3 p-3 sm:mb-4 sm:p-4"><div className="flex min-w-0 flex-col gap-1.5 sm:flex-row sm:items-baseline sm:justify-between sm:gap-3"><div className="min-w-0"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-muted-foreground">Outcome library</p><h2 className="mt-1 text-sm font-medium">Start from a business result</h2></div><span className="shrink-0 text-[10px] text-muted-foreground">{outcomes.length} governed packages</span></div><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{outcomes.map((outcome) => <div key={outcome.slug} className="min-w-0 rounded-md border border-foreground/10 p-2.5 sm:p-3"><p className="text-xs font-medium">{outcome.name}</p><p className="mt-1 text-[10px] leading-4 text-muted-foreground">{short(outcome.description, 130)}</p><div className="mt-2 flex flex-wrap gap-1.5 text-[9px] text-muted-foreground"><span className="rounded-sm border border-foreground/10 px-1.5 py-0.5">{outcome.department}</span><span className="rounded-sm border border-foreground/10 px-1.5 py-0.5">{outcome.evidenceRequired.length} evidence rules</span><span className="rounded-sm border border-foreground/10 px-1.5 py-0.5">{outcome.approvalPolicy}</span></div></div>)}</div></Card>}
    {offline ? <Card className="p-5 text-xs text-muted-foreground">Missions could not be loaded. Check the backend connection and retry.</Card> : <Card>
      {missions.length ? missions.map((mission) => { const isSelected = selected?.mission.id === mission.id; const proof = isSelected ? selected.proof : undefined; return <div key={mission.id} className="min-w-0 border-b border-foreground/10 p-3 last:border-0 sm:p-4">
        <button type="button" className="min-h-11 w-full min-w-0 text-left" onClick={() => void loadDetail(mission)} disabled={detailBusy === mission.id} aria-expanded={isSelected}>
          <div className="grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-start gap-2"><div className="min-w-0"><p className="text-xs font-medium leading-4">{mission.title}</p><p className="mt-1 font-mono text-[9px] leading-4 text-muted-foreground [overflow-wrap:anywhere]">{mission.id} · updated {date(mission.updatedAt)}</p></div><Status tone={tone(mission.status)}>{mission.status}</Status></div>
          <p className="mt-2 text-[11px] leading-[1.45rem] text-muted-foreground [overflow-wrap:anywhere]">{mission.nextAction || mission.checkpoint || mission.objective}</p><div className="mt-2 flex flex-wrap gap-x-2 gap-y-1 text-[10px] text-muted-foreground"><span>{mission.consumedSteps} slices</span><span>{mission.toolCalls} tool calls</span><span>${mission.cost.toFixed(4)}</span><span>{mission.steps.length} steps</span>{mission.activeStepIds?.length ? <span>{mission.activeStepIds.length} active branches</span> : null}</div>
        </button>
        {isSelected && <div className="mt-3 min-w-0 space-y-3 border-t border-foreground/10 pt-3 text-[11px] text-muted-foreground sm:mt-4 sm:space-y-4 sm:pt-4">
          <div className="min-w-0"><MarkdownMessage content={mission.objective} /><div className="mt-2 min-w-0"><p className="mb-1 font-medium text-foreground">Definition of done</p><MarkdownMessage content={mission.definitionOfDone} /></div></div>
          {mission.waiting && <div className="flex min-w-0 items-start gap-2 rounded-md border border-amber-500/30 bg-amber-500/5 p-2.5 sm:p-3"><Timer size={14} className="mt-0.5 shrink-0 text-amber-700" aria-hidden="true" /><p className="min-w-0 [overflow-wrap:anywhere]">Waiting for {mission.waiting.kind}{mission.waiting.provider ? ` from ${mission.waiting.provider}` : ""}{mission.waiting.providerEventId ? ` · ${mission.waiting.providerEventId}` : ""}</p></div>}
          <div className="grid gap-2 sm:grid-cols-3 sm:gap-3"><div className="min-w-0 rounded-md border border-foreground/10 p-2.5 sm:p-3"><p className="text-[9px] uppercase tracking-[0.16em] text-muted-foreground">Verification</p><p className="mt-1 flex items-center gap-1.5 text-foreground">{mission.verification?.verified ? <CheckCircle2 size={13} aria-hidden="true" /> : <CircleAlert size={13} aria-hidden="true" />} {mission.verification?.verified ? "Verified" : "Not verified"}</p><p className="mt-1 text-[10px]">{mission.verification?.mode === "strict" ? "Strict evidence gate" : "Legacy completion mode"}</p></div><div className="min-w-0 rounded-md border border-foreground/10 p-2.5 sm:p-3"><p className="text-[9px] uppercase tracking-[0.16em] text-muted-foreground">Budget</p><p className="mt-1 text-foreground">{mission.consumedSteps}/{mission.budget.maxSteps} slices</p><p className="mt-1 text-[10px] [overflow-wrap:anywhere]">{mission.toolCalls}/{mission.budget.maxToolCalls} tools · ${mission.cost.toFixed(4)} / ${mission.budget.maxCost.toFixed(4)}</p></div><div className="min-w-0 rounded-md border border-foreground/10 p-2.5 sm:p-3"><p className="text-[9px] uppercase tracking-[0.16em] text-muted-foreground">Proof</p><p className="mt-1 flex items-center gap-1.5 text-foreground"><ShieldCheck size={13} aria-hidden="true" /> {(proof?.evidence ?? mission.evidence ?? []).length} evidence records</p><p className="mt-1 text-[10px]">{selected.events.length} durable events</p></div></div>
          <div className="min-w-0 space-y-2"><div className="flex items-center gap-2 text-foreground"><GitBranch size={13} aria-hidden="true" /><span className="font-medium">Execution graph</span></div>{mission.steps.map((step) => <div key={step.id} className="min-w-0 rounded-md border border-foreground/10 px-2.5 py-2"><div className="grid min-w-0 grid-cols-[minmax(0,1fr)_auto] items-start gap-2"><span className="min-w-0 leading-4 text-foreground [overflow-wrap:anywhere]">{step.title}</span><span className="shrink-0 whitespace-nowrap rounded-full bg-foreground/[0.05] px-1.5 py-0.5 font-mono text-[8px] uppercase tracking-wide">{step.status}</span></div><div className="mt-1 min-w-0"><MarkdownMessage content={step.objective} /></div>{step.dependsOn.length > 0 && <p className="mt-1 text-[10px] leading-4 [overflow-wrap:anywhere]">Depends on {step.dependsOn.join(", ")}</p>}{step.evidence?.length ? <p className="mt-1 text-[10px] text-green-700">{step.evidence.length} evidence record{step.evidence.length === 1 ? "" : "s"}</p> : null}</div>)}</div>
          {selected.events.length > 0 && <div className="min-w-0"><p className="mb-2 font-medium text-foreground">Recent activity</p><div className="space-y-2">{selected.events.slice(-5).reverse().map((event) => <div key={event.id} className="grid min-w-0 gap-1 border-l border-foreground/15 pl-2.5 sm:grid-cols-[7.5rem_minmax(0,1fr)] sm:gap-2"><time className="whitespace-nowrap font-mono text-[9px] leading-4 text-muted-foreground" dateTime={new Date(event.at).toISOString()}>{date(event.at)}</time><div className="min-w-0"><MarkdownMessage content={event.message || event.type} /></div></div>)}</div></div>}
          <div className="flex flex-wrap gap-2 border-t border-foreground/10 pt-3">{["running", "waiting"].includes(mission.status) && <Button secondary disabled={busy === mission.id} onClick={() => void act(mission, "pause")}>Pause</Button>}{["paused", "blocked", "failed"].includes(mission.status) && <Button secondary disabled={busy === mission.id} onClick={() => void act(mission, "resume")}>Resume</Button>}{["blocked", "failed"].includes(mission.status) && <Button secondary disabled={busy === mission.id} onClick={() => void act(mission, "repair")}>Repair and resume</Button>}{!["completed", "cancelled"].includes(mission.status) && <Button secondary disabled={busy === mission.id} onClick={() => void act(mission, "cancel")}>Cancel</Button>}</div>
        </div>}
      </div>; }) : <p className="p-5 text-xs text-muted-foreground">No autonomous missions yet. Start one from Chat or the API when work should continue beyond one turn.</p>}
    </Card>}
  </div>;
}
