"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, CircleAlert, GitBranch, RefreshCw, ShieldCheck, Timer } from "lucide-react";
import { chuskyApi, type Mission, type MissionProof, type OutcomePackage } from "@/lib/chusky-api";
import { Button, Card, PageHeading, Status } from "./app-shell";
import { useLiveData } from "@/lib/live-sync";

const tone = (status: Mission["status"]): "green" | "amber" | "gray" => status === "completed" ? "green" : ["blocked", "failed", "paused", "waiting"].includes(status) ? "amber" : "gray";
const date = (value: number) => new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
const short = (value: string, max = 180) => value.length > max ? `${value.slice(0, max - 1)}…` : value;
type MissionDetail = { mission: Mission; proof?: MissionProof; events: Mission["events"] };

export function MissionsPage() {
  const [missions, setMissions] = useState<Mission[]>([]);
  const [selected, setSelected] = useState<MissionDetail>();
  const [offline, setOffline] = useState(false);
  const [busy, setBusy] = useState<string>();
  const [detailBusy, setDetailBusy] = useState<string>();
  const [outcomes, setOutcomes] = useState<OutcomePackage[]>([]);
  const load = async () => { setOffline(false); try { setMissions((await chuskyApi.missions.list()).data); } catch { setOffline(true); } };
  const loadDetail = async (mission: Mission) => { setDetailBusy(mission.id); try { const [fresh, proof, events] = await Promise.all([chuskyApi.missions.get(mission.id), chuskyApi.missions.proof(mission.id).catch(() => undefined), chuskyApi.missions.events(mission.id).catch(() => ({ data: mission.events }))]); setMissions((current) => current.map((item) => item.id === fresh.id ? fresh : item)); setSelected({ mission: fresh, proof, events: events.data }); } finally { setDetailBusy(undefined); } };
  useEffect(() => { void load(); void chuskyApi.outcomes.list().then((result) => setOutcomes(result.data)).catch(() => setOutcomes([])); }, []);
  useLiveData(load);
  const act = async (mission: Mission, action: "pause" | "resume" | "cancel" | "repair") => { setBusy(mission.id); try { const next = action === "repair" ? await chuskyApi.missions.repair(mission.id, { reason: "Operator requested mission recovery from the dashboard." }) : await chuskyApi.missions[action](mission.id); setMissions((current) => current.map((item) => item.id === next.id ? next : item)); await loadDetail(next); } finally { setBusy(undefined); } };
  return <>
    <PageHeading eyebrow="Autonomous work" title="Missions" description="Durable work with checkpoints, budgets, waits, evidence, and explicit recovery controls." action={<Button secondary onClick={() => void load()}><RefreshCw size={13} /> Refresh</Button>} />
    {outcomes.length > 0 && <Card className="mb-4 p-4"><div className="flex items-baseline justify-between gap-3"><div><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-muted-foreground">Outcome library</p><h2 className="mt-1 text-sm font-medium">Start from a business result</h2></div><span className="text-[10px] text-muted-foreground">{outcomes.length} governed packages</span></div><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{outcomes.map((outcome) => <div key={outcome.slug} className="border border-foreground/10 p-3"><p className="text-xs font-medium">{outcome.name}</p><p className="mt-1 text-[10px] leading-4 text-muted-foreground">{short(outcome.description, 130)}</p><div className="mt-2 flex flex-wrap gap-1.5 text-[9px] text-muted-foreground"><span className="border border-foreground/10 px-1.5 py-0.5">{outcome.department}</span><span className="border border-foreground/10 px-1.5 py-0.5">{outcome.evidenceRequired.length} evidence rules</span><span className="border border-foreground/10 px-1.5 py-0.5">{outcome.approvalPolicy}</span></div></div>)}</div></Card>}
    {offline ? <Card className="p-5 text-xs text-muted-foreground">Missions could not be loaded. Check the backend connection and retry.</Card> : <Card>
      {missions.length ? missions.map((mission) => { const isSelected = selected?.mission.id === mission.id; const proof = isSelected ? selected.proof : undefined; return <div key={mission.id} className="border-b border-foreground/10 p-4 last:border-0">
        <button type="button" className="w-full text-left" onClick={() => void loadDetail(mission)} disabled={detailBusy === mission.id}>
          <div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-xs font-medium">{mission.title}</p><p className="mt-1 font-mono text-[9px] text-muted-foreground">{mission.id} · updated {date(mission.updatedAt)}</p></div><Status tone={tone(mission.status)}>{mission.status}</Status></div>
          <p className="mt-2 text-[11px] leading-5 text-muted-foreground">{mission.nextAction || mission.checkpoint || mission.objective}</p><p className="mt-2 text-[10px] text-muted-foreground">{mission.consumedSteps} slices · {mission.toolCalls} tool calls · ${mission.cost.toFixed(4)} · {mission.steps.length} steps{mission.activeStepIds?.length ? ` · ${mission.activeStepIds.length} active branches` : ""}</p>
        </button>
        {isSelected && <div className="mt-4 space-y-4 border-t border-foreground/10 pt-4 text-[11px] text-muted-foreground">
          <div><p className="leading-5 text-foreground">{mission.objective}</p><p className="mt-2 leading-5"><span className="font-medium text-foreground">Definition of done:</span> {mission.definitionOfDone}</p></div>
          {mission.waiting && <div className="flex items-start gap-2 border border-amber-500/30 bg-amber-500/5 p-3"><Timer size={14} className="mt-0.5 shrink-0 text-amber-700" /><p>Waiting for {mission.waiting.kind}{mission.waiting.provider ? ` from ${mission.waiting.provider}` : ""}{mission.waiting.providerEventId ? ` · ${mission.waiting.providerEventId}` : ""}</p></div>}
          <div className="grid gap-3 sm:grid-cols-3"><div className="border border-foreground/10 p-3"><p className="text-[9px] uppercase tracking-[0.16em] text-muted-foreground">Verification</p><p className="mt-1 flex items-center gap-1.5 text-foreground">{mission.verification?.verified ? <CheckCircle2 size={13} /> : <CircleAlert size={13} />} {mission.verification?.verified ? "Verified" : "Not verified"}</p><p className="mt-1 text-[10px]">{mission.verification?.mode === "strict" ? "Strict evidence gate" : "Legacy completion mode"}</p></div><div className="border border-foreground/10 p-3"><p className="text-[9px] uppercase tracking-[0.16em] text-muted-foreground">Budget</p><p className="mt-1 text-foreground">{mission.consumedSteps}/{mission.budget.maxSteps} slices</p><p className="mt-1 text-[10px]">{mission.toolCalls}/{mission.budget.maxToolCalls} tools · ${mission.cost.toFixed(4)} / ${mission.budget.maxCost.toFixed(4)}</p></div><div className="border border-foreground/10 p-3"><p className="text-[9px] uppercase tracking-[0.16em] text-muted-foreground">Proof</p><p className="mt-1 flex items-center gap-1.5 text-foreground"><ShieldCheck size={13} /> {(proof?.evidence ?? mission.evidence ?? []).length} evidence records</p><p className="mt-1 text-[10px]">{selected.events.length} durable events</p></div></div>
          <div className="space-y-2"><div className="flex items-center gap-2 text-foreground"><GitBranch size={13} /><span className="font-medium">Execution graph</span></div>{mission.steps.map((step) => <div key={step.id} className="border border-foreground/10 px-2.5 py-2"><div className="flex justify-between gap-2"><span className="text-foreground">{step.title}</span><span className="font-mono text-[9px]">{step.status}</span></div><p className="mt-1 leading-4">{short(step.objective, 220)}</p>{step.dependsOn.length > 0 && <p className="mt-1 text-[10px]">Depends on {step.dependsOn.join(", ")}</p>}{step.evidence?.length ? <p className="mt-1 text-[10px] text-green-700">{step.evidence.length} evidence record{step.evidence.length === 1 ? "" : "s"}</p> : null}</div>)}</div>
          {selected.events.length > 0 && <div><p className="mb-2 font-medium text-foreground">Recent activity</p><div className="space-y-1.5">{selected.events.slice(-5).reverse().map((event) => <div key={event.id} className="flex gap-2 border-l border-foreground/15 pl-2.5"><span className="font-mono text-[9px] text-muted-foreground">{date(event.at)}</span><span>{event.message || event.type}</span></div>)}</div></div>}
          <div className="flex flex-wrap gap-2">{["running", "waiting"].includes(mission.status) && <Button secondary disabled={busy === mission.id} onClick={() => void act(mission, "pause")}>Pause</Button>}{["paused", "blocked", "failed"].includes(mission.status) && <Button secondary disabled={busy === mission.id} onClick={() => void act(mission, "resume")}>Resume</Button>}{["blocked", "failed"].includes(mission.status) && <Button secondary disabled={busy === mission.id} onClick={() => void act(mission, "repair")}>Repair and resume</Button>}{!["completed", "cancelled"].includes(mission.status) && <Button secondary disabled={busy === mission.id} onClick={() => void act(mission, "cancel")}>Cancel</Button>}</div>
        </div>}
      </div>; }) : <p className="p-5 text-xs text-muted-foreground">No autonomous missions yet. Start one from Chat or the API when work should continue beyond one turn.</p>}
    </Card>}
  </>;
}
