"use client";

import { useEffect, useState, type ReactNode } from "react";
import { Activity, AlertTriangle, Check, CircleDot, Clock3, Database, ExternalLink, Gauge, Radio, RefreshCw, Server, ShieldCheck, TriangleAlert, Wifi } from "lucide-react";
import { chuskyApi, type AccountOverview, type HealthSnapshot } from "@/lib/chusky-api";
import { Button, Card, PageHeading, Status } from "./app-shell";

const labels: Record<string, string> = { redis: "Redis persistence", qstash: "QStash workflows", sendblue: "Sendblue iMessage", telegram: "Telegram bot" };
const channelLabels: Record<string, string> = { telegram: "Telegram", cli: "CLI", slack: "Slack", whatsapp: "WhatsApp", sendblue: "Sendblue" };

function tone(value: string): "green" | "amber" | "gray" { return value === "ok" || value === "configured" ? "green" : value === "disabled" ? "gray" : "amber"; }
function formatTime(value?: string) { return value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "No failures recorded"; }

function HealthCard({ name, value, icon }: { name: string; value: string; icon: ReactNode }) {
  return <div className="flex items-center justify-between border-b border-foreground/10 py-4 last:border-0"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center border border-foreground/10 text-muted-foreground">{icon}</span><span className="text-sm">{name}</span></div><Status tone={tone(value)}>{value}</Status></div>;
}

function Loading() { return <Card className="flex items-center gap-3 p-8 text-sm text-muted-foreground"><RefreshCw size={16} className="animate-spin" /> Reading live service health…</Card>; }
function Offline({ retry }: { retry: () => void }) { return <Card className="flex flex-col items-start gap-4 border-amber-300/70 bg-amber-50 p-6"><Status tone="amber">Dashboard API unavailable</Status><p className="max-w-xl text-sm leading-relaxed text-amber-950/70">The UI is authenticated, but Chusky’s operations endpoint could not be reached. Check the backend URL and service health, then try again.</p><Button secondary onClick={retry}><RefreshCw size={14} /> Retry</Button></Card>; }

export function OperationsDashboard({ deliveryOnly = false }: { deliveryOnly?: boolean }) {
  const [health, setHealth] = useState<HealthSnapshot>();
  const [account, setAccount] = useState<AccountOverview>();
  const [offline, setOffline] = useState(false);
  const load = async () => { setOffline(false); try { const [nextHealth, nextAccount] = await Promise.all([chuskyApi.health.get(), chuskyApi.account.get()]); setHealth(nextHealth); setAccount(nextAccount); } catch { setOffline(true); } };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30_000); return () => window.clearInterval(timer); }, []);

  return <>
    <PageHeading eyebrow={deliveryOnly ? "Delivery control" : "Operations center"} title={deliveryOnly ? "Delivery you can trust." : "Everything is in view."} description={deliveryOnly ? "Watch the channels and failure signals that move work from Chusky to your people." : "A live read on Chusky’s runtime, connected channels, and durable delivery path."} action={<Button secondary onClick={() => void load()}><RefreshCw size={14} /> Refresh</Button>} />
    {offline ? <Offline retry={() => void load()} /> : !health ? <Loading /> : <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-4 border border-foreground/10 bg-background px-5 py-4"><div className="flex items-center gap-3"><span className={`flex h-9 w-9 items-center justify-center rounded-full ${health.ok ? "bg-emerald-100 text-emerald-700" : "bg-amber-100 text-amber-700"}`}><Activity size={17} /></span><div><p className="text-sm font-medium">System {health.status}</p><p className="mt-1 text-xs text-muted-foreground">Auto-refreshes every 30 seconds · Last checked just now</p></div></div><Status tone={health.ok ? "green" : "amber"}>{health.persistence === "redis" ? "Durable storage" : "Development storage"}</Status></div>
      {!deliveryOnly && <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Delivery failures" value={String(health.monitoring.counters.delivery_failure ?? 0)} detail="Since this process started" icon={<TriangleAlert size={15} />} /><Metric label="Workflow failures" value={String(health.monitoring.counters.workflow_failure ?? 0)} detail="Durable runs needing review" icon={<Clock3 size={15} />} /><Metric label="Provider failures" value={String(health.monitoring.counters.provider_failure ?? 0)} detail="API or connectivity errors" icon={<Radio size={15} />} /><Metric label="Redis failures" value={String(health.monitoring.counters.redis_failure ?? 0)} detail="Persistence incidents" icon={<Database size={15} />} /></div>}
      <div className="grid gap-6 xl:grid-cols-[1.05fr_1fr]">
        <Card className="p-5"><div className="mb-2 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Runtime checks</p><h2 className="mt-2 font-display text-2xl">The foundation</h2></div><Server size={18} className="text-muted-foreground" /></div>{Object.entries(health.checks).map(([key, value]) => <HealthCard key={key} name={labels[key] ?? key} value={value} icon={key === "redis" ? <Database size={14} /> : key === "qstash" ? <Clock3 size={14} /> : key === "sendblue" ? <Radio size={14} /> : <Wifi size={14} />} />)}</Card>
        <Card className="p-5"><div className="mb-2 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Connected channels</p><h2 className="mt-2 font-display text-2xl">Where Chusky can reach you</h2></div><Gauge size={18} className="text-muted-foreground" /></div>{Object.entries(health.channels).map(([key, enabled]) => <div key={key} className="flex items-center justify-between border-b border-foreground/10 py-4 last:border-0"><div className="flex items-center gap-3"><span className={`h-2 w-2 rounded-full ${enabled ? "bg-emerald-500" : "bg-foreground/20"}`} /><span className="text-sm">{channelLabels[key] ?? key}</span></div><span className="text-xs text-muted-foreground">{enabled ? "Enabled" : "Not enabled"}</span></div>)}</Card>
      </div>
      <Card className="p-5"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Latest incident</p><h2 className="mt-2 font-display text-2xl">{health.monitoring.lastFailure ? "Needs a closer look" : "Quiet by design"}</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{health.monitoring.lastFailure ? `${health.monitoring.lastFailure.type ?? "Failure"} · ${health.monitoring.lastFailure.message ?? "See service logs for details."}` : "No runtime failures have been recorded by this process. Durable provider retries remain visible in the service logs."}</p></div><div className="shrink-0 text-left md:text-right"><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Last event</p><p className="mt-2 text-xs">{formatTime(health.monitoring.lastFailure?.at)}</p></div></div></Card>
      {deliveryOnly && <Card className="p-5"><div className="mb-4 flex items-center justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.18em] text-muted-foreground">Recent deliveries</p><h2 className="mt-2 font-display text-2xl">What actually left Chusky</h2></div><ExternalLink size={17} className="text-muted-foreground" /></div>{account?.deliveries.length ? <div className="divide-y divide-foreground/10">{account.deliveries.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-3 text-xs"><div><p className="font-medium">{item.provider} · {item.kind}</p><p className="mt-1 text-muted-foreground">{formatTime(item.deliveredAt || item.updatedAt)} · {item.attempts} attempt{item.attempts === 1 ? "" : "s"}</p></div><Status tone={item.status === "delivered" ? "green" : item.status === "failed" ? "amber" : "gray"}>{item.status}</Status></div>)}</div> : <p className="text-sm text-muted-foreground">No outbound deliveries have been recorded for this account yet.</p>}</Card>}
      <div className="flex flex-wrap gap-2 text-xs text-muted-foreground"><ShieldCheck size={14} className="text-emerald-600" /> Secrets are never returned to the dashboard. <span className="mx-1">·</span> <ExternalLink size={13} /> Failure counters reset when the process restarts; durable workflow state remains in Redis.</div>
    </div>}
  </>;
}

function Metric({ label, value, detail, icon }: { label: string; value: string; detail: string; icon: ReactNode }) { return <Card className="p-5"><div className="flex items-center justify-between text-muted-foreground"><p className="font-mono text-[10px] uppercase tracking-[0.16em]">{label}</p>{icon}</div><p className="mt-5 font-display text-4xl">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></Card>; }
