"use client";

import { useEffect, useState } from "react";
import { ChevronRight, FileCode2, FileText, Folder, LoaderCircle, RefreshCw, Search, X } from "lucide-react";
import { chuskyApi, type Skill, type SkillFile } from "@/lib/chusky-api";
import { Button, Card, PageHeading } from "./app-shell";

export function SkillsPage() {
  const [items, setItems] = useState<Skill[]>([]);
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string>();
  const [open, setOpen] = useState<{ skill: Skill; files: SkillFile[]; selected?: SkillFile }>();
  const load = async (search = query) => { setLoading(true); setError(undefined); try { setItems((await chuskyApi.skills.list(search, 100)).data); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not load skills."); } finally { setLoading(false); } };
  useEffect(() => { void load(""); }, []);
  const openSkill = async (skill: Skill) => { try { const files = (await chuskyApi.skills.files(skill.name)).data; setOpen({ skill, files, selected: files.find((file) => file.path === "SKILL.md") }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not open this skill."); } };
  const read = async (file: SkillFile) => { if (!open) return; try { setOpen({ ...open, selected: await chuskyApi.skills.read(open.skill.name, file.path) }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not read this file."); } };
  return <>
    <PageHeading eyebrow="Agent knowledge" title="Skills" description="Browse the trusted skills installed in .chusky/skills. Open a skill folder to inspect SKILL.md and any supporting files the agent can use." action={<Button secondary onClick={() => void load()}><RefreshCw size={13} /> Refresh</Button>} />
    <div className="mb-5 flex min-h-9 items-center gap-2 border border-foreground/15 bg-background px-2.5"><Search size={14} className="text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void load(query); }} placeholder="Search installed skills" className="min-w-0 flex-1 bg-transparent text-xs outline-none" /><button type="button" onClick={() => void load(query)} className="text-[10px] text-muted-foreground hover:text-foreground">Search</button></div>
    {error && <Card className="mb-4 border-amber-300 bg-amber-50 p-3.5 text-xs text-amber-900">{error}</Card>}
    {loading && !items.length ? <Card className="flex items-center gap-2 p-5 text-xs text-muted-foreground"><LoaderCircle size={15} className="animate-spin" /> Loading the skills catalogue…</Card> : items.length ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{items.map((skill) => <button type="button" key={skill.name} onClick={() => void openSkill(skill)} className="group min-w-0 border border-foreground/10 bg-background p-4 text-left transition-colors hover:border-foreground/35"><div className="flex items-start gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-foreground/10 bg-amber-50 text-amber-800"><Folder size={16} /></span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className="truncate text-sm font-medium">{skill.name}</span><ChevronRight size={14} className="shrink-0 text-muted-foreground transition-transform group-hover:translate-x-0.5" /></span><span className="mt-1.5 block line-clamp-3 text-[11px] leading-5 text-muted-foreground">{skill.description}</span><span className="mt-3 block truncate font-mono text-[9px] text-muted-foreground">{skill.path}</span></span></div></button>)}</div> : <Card className="p-5 text-xs text-muted-foreground">No skills matched this search.</Card>}
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-3 sm:p-5" role="dialog" aria-modal="true"><Card className="flex max-h-[90vh] w-full max-w-5xl min-w-0 flex-col overflow-hidden shadow-2xl"><div className="flex items-start justify-between gap-3 border-b border-foreground/10 p-4"><div className="min-w-0"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-muted-foreground">.chusky/skills</p><h2 className="mt-1 truncate font-display text-xl">{open.skill.name}</h2><p className="mt-1 text-[11px] text-muted-foreground">{open.skill.description}</p></div><button type="button" onClick={() => setOpen(undefined)} className="p-1 text-muted-foreground hover:text-foreground" aria-label="Close skill viewer"><X size={16} /></button></div><div className="grid min-h-0 flex-1 md:grid-cols-[260px_1fr]"><div className="overflow-y-auto border-b border-foreground/10 p-2 md:border-b-0 md:border-r"><p className="px-2.5 py-2 font-mono text-[9px] uppercase tracking-[0.16em] text-muted-foreground">Files</p>{open.files.map((file) => <button type="button" key={file.path} onClick={() => void read(file)} className={`flex w-full items-center gap-2 px-2.5 py-2 text-left text-[11px] ${open.selected?.path === file.path ? "bg-foreground text-background" : "hover:bg-foreground/5"}`}><FileCode2 size={12} className="shrink-0" /><span className="truncate">{file.path}</span></button>)}</div><div className="min-h-0 overflow-auto p-4">{open.selected?.binary ? <p className="text-xs text-muted-foreground">This file is binary and cannot be previewed as text.</p> : open.selected ? <pre className="whitespace-pre-wrap break-words font-mono text-[11px] leading-5">{open.selected.content || ""}</pre> : <div className="flex items-center gap-2 text-xs text-muted-foreground"><FileText size={14} /> Select a file to inspect it.</div>}</div></div></Card></div>}
  </>;
}
